.TH IMAGE2ORB 3 "$Date: 2004/08/04 15:24:49 $"
.SH NAME
image2orb \- experimental perl routine to put image on an orb
.SH SYNOPSIS
.nf
use image2orb;

image2orb( $orb, $time, $srcname, $description, $imgdata, $format )

$image2orb::Suffix = "/EXP/IMG";
$image2orb::Current_Version = 110;
$image2orb::ORB_MAX_DATA_BYTES = 1000000;
$image2orb::Description_length = 64;
$image2orb::Format_length = 25;

.fi
.SH DESCRIPTION
Image2orb takes a file descriptor for an open orb connection,
a raw image-data block together with epoch-time timestamp, source-name,
and a description string up to 64 characters in length, and puts the
the image in version 1.10 format (i.e. short int 110) on the orb. 
If the format is not explicitly specified, image2orb attempts to 
infer it by comparing the blob to a few well-known magic numbers
(JPEG, GIF, PNG, PBM, PGM, PPM, TIFF).

image2orb expects a sourcename suffix of /EXP/IMG. If another suffix is 
present, image2orb will complain and return -1. If no suffix is present
on the sourcename, image2orb will add one. 

.SH OPTIONS
.SH FILES
.SH ENVIRONMENT
.SH PARAMETER FILE
.SH EXAMPLE
.ft CW
.in 2c
.nf
.fi
.in
.ft R
.SH RETURN VALUES
0 on success; -1 for failure
.SH LIBRARY
.SH DIAGNOSTICS
.SH "SEE ALSO"
.nf
perlorb(3p)
.fi
.SH "BUGS AND CAVEATS"
The constants Suffix, Current_Version, ORB_MAX_DATA_BYTES,
Description_length, and Format_length are advisory and not recommended
to be changed.
.SH AUTHOR
.nf
Kent Lindquist
Lindquist Consulting
.fi
.\" $Id: image2orb.3,v 1.4 2004/08/04 15:24:49 danq Exp $
