PF  = db2ims.pf
PF += db2sync.pf
PF += dbcalibrate.pf
PF += dbcalibrate_HH.pf
PF += dbcentral.pf
PF += dbevproc.pf
PF += dbloc2_anza.pf
PF += dbloc2_usarray.pf
PF += dbverify.pf
PF += elog.pf
PF += fix_sync.pf
PF += mk_dbops.pf
PF += mk_dmc_files.pf
PF += orbserver.pf
PF += orbserver_names.pf
PF += orbxfer2.pf
PF += proc_gaps.pf
PF += smartpick.pf
PF += sta_final_prep.pf
PF += sta_final_to_dmc.pf
PF += sta_final_verify.pf
PF += sta_final_wfdisc.pf
PF += stations.pf
PF += wffil.pf

include $(ANFMAKE)
