PF = \
   db2ims.pf \
   db2sync.pf \
   dbcalibrate.pf \
   dbcentral.pf \
   dbe.tk \
   dbevproc.pf \
   dbloc2_anza.pf \
   dbloc2_usarray.pf \
   dbverify.pf \
   elog.pf \
   fix_sync.pf \
   mk_dbops.pf \
   mk_dmc_files.pf \
   orbxfer2.pf \
   proc_gaps.pf \
   q330_calibration.pf \
   smartpick.pf \
   sta_final_prep.pf \
   sta_final_to_dmc.pf \
   sta_final_verify.pf \
   sta_final_wfdisc.pf \
   stations.pf

include $(ANFMAKE)
