# Install Python module python-rrdtool
# Requires:
# * C header files for the rrdtool package, available as rrdtool-devel on
# RedHat/CentOS
MODULE_NAME = python-rrdtool
MODULE_VERSION = 1.4.7
include ../lib/pymodule.mk

