.TH HFRADARTOOLS 3P "$Date: 2007/03/23 07:03:24 $"
.SH NAME
hfradartools \- Tools to handle HFRADAR ocean surface-current data
.SH SYNOPSIS
.nf
use hfradartools;

.fi
.SH DESCRIPTION
This is an intentionally undocumented library of internal routines 
for orbhfradar2db(1).

.SH OPTIONS
.SH FILES
.SH ENVIRONMENT
.SH PARAMETER FILE
.SH EXAMPLE
.in 2c
.ft CW
.nf
.fi
.ft R
.in
.SH RETURN VALUES
.SH LIBRARY
.SH ATTRIBUTES
.SH DIAGNOSTICS
.SH "SEE ALSO"
.nf
.fi
.SH "BUGS AND CAVEATS"
.SH AUTHOR
.nf
Kent Lindquist
Lindquist Consulting
kent@lindquistconsulting.com

.fi
.\" $Id: hfradartools.3p,v 1.1 2007/03/23 07:03:24 lindquis Exp $
