
DATA = hfradar2orb.pm \
       codartools.pm \
       weratools.pm \
       hfradartools.pm

DATADIR = perl
PF = hfradar2orb_pm.pf

MAN3P = hfradar2orb.3p codartools.3p weratools.3p hfradartools.3p

include $(ANTELOPEMAKE)
