.TH CODARTOOLS 3P "$Date: 2008/12/07 19:19:46 $"
.SH NAME
weratools \- Tools to handle WERA ocean surface-current data
.SH SYNOPSIS
.nf
use weratools;

$rc = weratools::is_wera( @datablock );

$weratools::Verbose;

.fi
.SH DESCRIPTION
These routines support the acquisition and processing of high-frequency coastal
radar data, tailored for the WERA instrument instead of the CODAR instrument. 

The \fBis_wera\fP function provides a simple test to evaluate whether a data block 
came from a WERA datalogger. 
.SH OPTIONS
.SH FILES
.SH ENVIRONMENT
.SH PARAMETER FILE
.SH EXAMPLE
.in 2c
.ft CW
.nf
.fi
.ft R
.in
.SH RETURN VALUES
.SH LIBRARY
.SH ATTRIBUTES
.SH DIAGNOSTICS
.SH "SEE ALSO"
.nf
codartools(3p), convert_rb2lluv(1), hfradar2orb(3p), hfradar2orb(1)
.fi
.SH "BUGS AND CAVEATS"

.SH AUTHOR
.nf
Kent Lindquist
Lindquist Consulting, Inc.
kent@lindquistconsulting.com

and

Mark Otero 
Marine Physics Laboratory
University of California, San Diego
motero@mpl.ucsd.edu

This code has been developed in support of the HF-Radar National
Network and the state of California's Coastal Ocean Currents
Monitoring Program (COCMP).
										
Please email motero@mpl.ucsd.edu to report any bugs.
Include sample radial files and describe the problem observed.

.fi
.\" $Id: weratools.3p,v 1.2 2008/12/07 19:19:46 lindquis Exp $
