.TH ICE92ORB 1 "$Date: 2003/04/02 19:10:13 $"
.SH NAME
ice92orb \- communicate with ICE-9 data logger and create MGENC packets
.SH SYNOPSIS
.nf
ice92orb [-V] [-p listenport] [-S state/file] -o $ORB
.fi
.SH DESCRIPTION
ice92orb listens on a port (default 14028) for an incoming connection from
an ICE-9 data logger. ICE-9 data loggers are traditionally used for Strain 
Monitoring. Each instance of ice92orb accepts one incoming connection and 
gathers data from the logger. If a state file is specified it will use that 
to inform the ICE-9 system what data has already been received. If that 
file is specified but doesn't exist then ice92orb will create the file. If
the file is not specified or it is an empty file, the ICE-9 data logger 
will be asked to send all of the available data. 

In order for this program to function you must specify an orb to send the 
data to. The source name used in the antelope system is configured in the 
ICE-9 data logger.
.SH OPTIONS
.nf
-V		 	print version and usage, then exit
-p listenport	listen for incomming connection on this port, 
  	 		instead of the default (14028).
-S state/file	use this state file for saving ICE-9 comm state
-o $ORB		send data to this orb (required option)
.fi
.SH FILES
.SH ENVIRONMENT
.SH PARAMETER FILE
.nf
roadnet-orb% cat ~rt/state/lab4.state
ip_address      132.239.152.51
last_seqnum     88379
last_timestamp  1049307545
roadnet-orb% 
.fi
.SH EXAMPLE
 ice92orb -p 14050 -S state/ice92orb -o :
.ft CW
.in 2c
.nf
.fi
.in
.ft R
.SH RETURN VALUES
.SH LIBRARY
Requires antelope 4.5 or newer.
.SH DIAGNOSTICS
Making this application with DEBUG defined will create an executable with 
ShowPkt() enabled. The accompanying application junk2pfo is available to 
create a fake ICE-9 stream for testing new revisions of ice92orb.
.SH "SEE ALSO"
.nf
.fi
.SH "BUGS AND CAVEATS"
This application expects to have the same datalogger connecting to the same 
port. So if a different data logger (IP address) connects it will accept 
the connection and use the ICE-9 comm parameters already stored in the state 
file. The only notice you will get is that it will give you a warning that 
the IP address of the data logger has changed.
.SH AUTHOR
.nf
Todd Hansen
UCSD/ROADNet Project
.fi
