.TH ICE92ORB.PF 5 "$Date: 2003/05/21 22:50:48 $"
.SH NAME
ice92orb.pf \- example parameter file for ice92orb(1)
.SH SYNOPSIS
.nf
ice92orb can include calibration data into the data packets, this is the mechanism to do that.
.fi
.SH DESCRIPTION
The parameter file is not used, unless it is specified on ice92orb's command line. The parameter file is searched each time a calibration value is needed. Once a calibration value is needed, ice92orb searches for it by looking for a calibration in the following values: calib_net_sta_chan, calib_net_sta, calib_net, calib. It takes the first value it sees. So you can define a calibration value for the whole file and then define a subset of calibrations for particular sensors, all in the same file. If no calibration value is found it will use the null calibration value of 0. Calibration is a floating point number that is multiplied by the instrument value to get a representative unit. In this case, the final units are strain (nm/nm).
.SH EXAMPLE CONFIG FILE
.nf
roadnet-orb% cat ice92orb.pf
calib 1.0
calib_PF 1.0
calib_PF_GVS 1.0
calib_PF_GVS_3 1.0
calib_PF_GVS_5 1.0
roadnet-orb% 
.fi
.SH LIBRARY
ice92orb requires antelope 4.5 or newer.
.SH DIAGNOSTICS
.SH "SEE ALSO"
.nf
ice92orb(1)
.fi
.SH "BUGS AND CAVEATS"
.SH AUTHOR
.nf
Todd Hansen
UCSD/ROADNet Project
.fi
