DATADIR = python/anf
DATA = __init__.pyc \
	   deep_auto_convert.py \
	   anfdb_collections.py \
	   logging_helper.py \
	   str2bool.py \
	   anfstock.py \
	   anftr.py \
	   anfdb.py \
	   anfpf.py

include $(ANFMAKE)
