DATADIR = python/anf
#DATA  = __init__.py
#DATA += eloghandler.py
#DATA += str2bool.py
#DATA += logutil.py
#DATA += orbpfparser.py

CLEAN = testrunner

MAN3Y = pythoneloghandler.3y

include $(ANFMAKE)

test: testrunner FORCE
	@echo Running Python Tests:
	@./testrunner

DIRS = anf

FORCE:
