DATA= Images0.2 \
      Images0.3 \
      sitephotos0.1 \
      sitephotos0.2 \
      Codar0.1 \
      Codar0.2 \
      Codar0.3 \
      nmea0.1 \
      wfsrb1.0

DATADIR=schemas

include $(ANTELOPEMAKE)
