.TH ANFMAKEFILE 5 "$Date: 2008/04/07 13:02:15 $"
.SH NAME
anfmakefile \- ANF Makefile format
.SH DESCRIPTION
The anf makefile is an extension of the Antelope Makefiles documented 
in antelopemakefile(5). They behave exactly the same way as Antelope makefiles,
with the exception that they use the ANFMAKE environment variable 
instead of ANTELOPEMAKE to point to their make rules, and they install to 
/opt/anf/X.X instead of /opt/antelope/X.X. 
.SH FILES
.SH ENVIRONMENT
.IP ANF
This is the ANF environment variable, exactly analogous to the ANTELOPE 
environment variable as documented in antelopeenv(5). It indicates the 
base directory for an ANF release. It uses the same version number as the 
Antelope installation since the ANF code is compiled against and therefore
dependent on specific Antelope versions. This environment variable 
is usually set automatically, for example by sourcing the file
/opt/anf/4.8/setup.csh. 
.IP ANFMAKE
This is the ANFMAKE environment variable, exactly analogous to the ANTELOPEMAKE
environment variable as documented in antelopeenv(5) and antelopemakefile(5).
.SH PARAMETER FILE
.SH EXAMPLE
.in 2c
.ft CW
.nf
.fi
.ft R
.in
.SH DIAGNOSTICS
.SH "SEE ALSO"
.nf
antelopemakefile(5)
.fi
.SH "BUGS AND CAVEATS"
.SH AUTHOR
.nf
Kent Lindquist
Lindquist Consulting, Inc.
.fi
