# Instrument responses for Chaparral MET stations

DATADIR= instruments/sn/chaparral
DATA=\
3655.pf \
3656.pf \
3660.pf \
3661.pf \
3662.pf \
3664.pf \
3666.pf \
3668.pf \
3669.pf \
3670.pf

include $(ANTELOPEMAKE)
SUBDIR= /local
