# Makefile to install Python modules under $ANF
#

include $(ANFMAKE)
DIRS  = beautifulsoup 
DIRS += pyflickr
DIRS += twisted
DIRS += matplotlib
DIRS += numpy
DIRS += obspycore
DIRS += obspymseed
DIRS += obspysac
DIRS += obspygse
DIRS += obspyimaging
