DATADIR= php

# The files to be installed should appear in a 'DATA' 
# statement as follows:
#
# DATA= file1.php \
#       file2.php \
#       file3.inc \
#       file4.css \
#       file5.php

DATA= 

include $(ANTELOPEMAKE)
